//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace x_template_xPlcConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("x_template_xPlcConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  already exist! .
        /// </summary>
        public static string ____already_exist____ {
            get {
                return ResourceManager.GetString("____already_exist____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Consecutive failure) The number of any recurring failure count has been reached!.
        /// </summary>
        public static string ____Consecutive_failure__The_number_of_any_recurring_failure_count_has_been_reached___ {
            get {
                return ResourceManager.GetString("____Consecutive_failure__The_number_of_any_recurring_failure_count_has_been_reach" +
                        "ed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Consecutive failure) The number of same recurring failure count has been reached! .
        /// </summary>
        public static string ____Consecutive_failure__The_number_of_same_recurring_failure_count_has_been_reached____ {
            get {
                return ResourceManager.GetString("____Consecutive_failure__The_number_of_same_recurring_failure_count_has_been_reac" +
                        "hed____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _cu00x.
        /// </summary>
        public static string ____cu00x__ {
            get {
                return ResourceManager.GetString("____cu00x__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is founded but assigned value is empty! Would you like continue? .
        /// </summary>
        public static string ____is_founded_but_assigned_value_is_empty__Would_you_like_continue____ {
            get {
                return ResourceManager.GetString("____is_founded_but_assigned_value_is_empty__Would_you_like_continue____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is inactive! .
        /// </summary>
        public static string ____is_inactive____ {
            get {
                return ResourceManager.GetString("____is_inactive____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not founded ! Would you like assign right now? .
        /// </summary>
        public static string ____is_not_founded___Would_you_like_assign_right_now____ {
            get {
                return ResourceManager.GetString("____is_not_founded___Would_you_like_assign_right_now____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not founded due collection is empty ! Would you like assign right now? .
        /// </summary>
        public static string ____is_not_founded_due_collection_is_empty___Would_you_like_assign_right_now____ {
            get {
                return ResourceManager.GetString("____is_not_founded_due_collection_is_empty___Would_you_like_assign_right_now____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was not founnd! Would you like still like to continue? .
        /// </summary>
        public static string ____was_not_founnd__Would_you_like_still_like_to_continue____ {
            get {
                return ResourceManager.GetString("____was_not_founnd__Would_you_like_still_like_to_continue____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW TAG  EXAMPLE.
        /// </summary>
        public static string ___ADD_NEW_TAG__EXAMPLE__ {
            get {
                return ResourceManager.GetString("___ADD_NEW_TAG__EXAMPLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Tag.
        /// </summary>
        public static string ___Adding_Tag__ {
            get {
                return ResourceManager.GetString("___Adding_Tag__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air pressure.
        /// </summary>
        public static string ___Air_pressure__ {
            get {
                return ResourceManager.GetString("___Air_pressure__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air pressure is not sufficient!.
        /// </summary>
        public static string ___Air_pressure_is_not_sufficient___ {
            get {
                return ResourceManager.GetString("___Air_pressure_is_not_sufficient___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ___All__ {
            get {
                return ResourceManager.GetString("___All__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All keys in automatic.
        /// </summary>
        public static string ___All_keys_in_automatic__ {
            get {
                return ResourceManager.GetString("___All_keys_in_automatic__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All keys in normal.
        /// </summary>
        public static string ___All_keys_in_normal__ {
            get {
                return ResourceManager.GetString("___All_keys_in_normal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any button.
        /// </summary>
        public static string ___Any_button__ {
            get {
                return ResourceManager.GetString("___Any_button__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any key in manual.
        /// </summary>
        public static string ___Any_key_in_manual__ {
            get {
                return ResourceManager.GetString("___Any_key_in_manual__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any key in service.
        /// </summary>
        public static string ___Any_key_in_service__ {
            get {
                return ResourceManager.GetString("___Any_key_in_service__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any key in step.
        /// </summary>
        public static string ___Any_key_in_step__ {
            get {
                return ResourceManager.GetString("___Any_key_in_step__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any present.
        /// </summary>
        public static string ___Any_present__ {
            get {
                return ResourceManager.GetString("___Any_present__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any station in automatic mode.
        /// </summary>
        public static string ___Any_station_in_automatic_mode__ {
            get {
                return ResourceManager.GetString("___Any_station_in_automatic_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any station in manual mode.
        /// </summary>
        public static string ___Any_station_in_manual_mode__ {
            get {
                return ResourceManager.GetString("___Any_station_in_manual_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any station in step mode.
        /// </summary>
        public static string ___Any_station_in_step_mode__ {
            get {
                return ResourceManager.GetString("___Any_station_in_step_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any station is grounding.
        /// </summary>
        public static string ___Any_station_is_grounding__ {
            get {
                return ResourceManager.GetString("___Any_station_is_grounding__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any station is holded.
        /// </summary>
        public static string ___Any_station_is_holded__ {
            get {
                return ResourceManager.GetString("___Any_station_is_holded__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Value.
        /// </summary>
        public static string ___Assigned_Value__ {
            get {
                return ResourceManager.GetString("___Assigned_Value__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autmatic mode allowed.
        /// </summary>
        public static string ___Autmatic_mode_allowed__ {
            get {
                return ResourceManager.GetString("___Autmatic_mode_allowed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string ___Auto__ {
            get {
                return ResourceManager.GetString("___Auto__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMAT.
        /// </summary>
        public static string ___AUTOMAT__ {
            get {
                return ResourceManager.GetString("___AUTOMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMAT ALL.
        /// </summary>
        public static string ___AUTOMAT_ALL__ {
            get {
                return ResourceManager.GetString("___AUTOMAT_ALL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automat mode has been done..
        /// </summary>
        public static string ___Automat_mode_has_been_done___ {
            get {
                return ResourceManager.GetString("___Automat_mode_has_been_done___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automat mode has been invoked..
        /// </summary>
        public static string ___Automat_mode_has_been_invoked___ {
            get {
                return ResourceManager.GetString("___Automat_mode_has_been_invoked___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automat task.
        /// </summary>
        public static string ___Automat_task__ {
            get {
                return ResourceManager.GetString("___Automat_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string ___Automatic__ {
            get {
                return ResourceManager.GetString("___Automatic__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic mode is not possibe to set(All keys must be in NORMAL and AUTO!).
        /// </summary>
        public static string ___Automatic_mode_is_not_possibe_to_set_All_keys_must_be_in_NORMAL_and_AUTO____ {
            get {
                return ResourceManager.GetString("___Automatic_mode_is_not_possibe_to_set_All_keys_must_be_in_NORMAL_and_AUTO____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic mode is set(Step mode is disabled)!.
        /// </summary>
        public static string ___Automatic_mode_is_set_Step_mode_is_disabled____ {
            get {
                return ResourceManager.GetString("___Automatic_mode_is_set_Step_mode_is_disabled____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average clean cycle time .
        /// </summary>
        public static string ___Average_clean_cycle_time___ {
            get {
                return ResourceManager.GetString("___Average_clean_cycle_time___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average cycle time .
        /// </summary>
        public static string ___Average_cycle_time___ {
            get {
                return ResourceManager.GetString("___Average_cycle_time___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average cycle time filter constant.
        /// </summary>
        public static string ___Average_cycle_time_filter_constant__ {
            get {
                return ResourceManager.GetString("___Average_cycle_time_filter_constant__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic door.
        /// </summary>
        public static string ___Basic_door__ {
            get {
                return ResourceManager.GetString("___Basic_door__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brings the device into basic position..
        /// </summary>
        public static string ___Brings_the_device_into_basic_position___ {
            get {
                return ResourceManager.GetString("___Brings_the_device_into_basic_position___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonAuto .
        /// </summary>
        public static string ___ButtonAuto___ {
            get {
                return ResourceManager.GetString("___ButtonAuto___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonAutoLight.
        /// </summary>
        public static string ___ButtonAutoLight__ {
            get {
                return ResourceManager.GetString("___ButtonAutoLight__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonGround .
        /// </summary>
        public static string ___ButtonGround___ {
            get {
                return ResourceManager.GetString("___ButtonGround___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonGroundLight.
        /// </summary>
        public static string ___ButtonGroundLight__ {
            get {
                return ResourceManager.GetString("___ButtonGroundLight__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonRecover.
        /// </summary>
        public static string ___ButtonRecover__ {
            get {
                return ResourceManager.GetString("___ButtonRecover__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonStartLight.
        /// </summary>
        public static string ___ButtonStartLight__ {
            get {
                return ResourceManager.GetString("___ButtonStartLight__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonStopLight.
        /// </summary>
        public static string ___ButtonStopLight__ {
            get {
                return ResourceManager.GetString("___ButtonStopLight__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonSuspend.
        /// </summary>
        public static string ___ButtonSuspend__ {
            get {
                return ResourceManager.GetString("___ButtonSuspend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        public static string ___Carrier__ {
            get {
                return ResourceManager.GetString("___Carrier__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check general condition to recover zone (ControlVoltage, EStops, Presure...)!.
        /// </summary>
        public static string ___Check_general_condition_to_recover_zone__ControlVoltage__EStops__Presure_______ {
            get {
                return ResourceManager.GetString("___Check_general_condition_to_recover_zone__ControlVoltage__EStops__Presure______" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check general condition to suspned zone (ControlVoltage,EStops,Presure...)!.
        /// </summary>
        public static string ___Check_general_condition_to_suspned_zone__ControlVoltage_EStops_Presure_______ {
            get {
                return ResourceManager.GetString("___Check_general_condition_to_suspned_zone__ControlVoltage_EStops_Presure_______", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean loop time.
        /// </summary>
        public static string ___Clean_loop_time__ {
            get {
                return ResourceManager.GetString("___Clean_loop_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear step mode.
        /// </summary>
        public static string ___Clear_step_mode__ {
            get {
                return ResourceManager.GetString("___Clear_step_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ___Closed__ {
            get {
                return ResourceManager.GetString("___Closed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string ___Config__ {
            get {
                return ResourceManager.GetString("___Config__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Buttons .
        /// </summary>
        public static string ___Control_Buttons___ {
            get {
                return ResourceManager.GetString("___Control_Buttons___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel.
        /// </summary>
        public static string ___Control_panel__ {
            get {
                return ResourceManager.GetString("___Control_panel__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control voltage.
        /// </summary>
        public static string ___Control_voltage__ {
            get {
                return ResourceManager.GetString("___Control_voltage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ___Created__ {
            get {
                return ResourceManager.GetString("___Created__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CU00x.
        /// </summary>
        public static string ___CU00x__ {
            get {
                return ResourceManager.GetString("___CU00x__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle time.
        /// </summary>
        public static string ___Cycle_time__ {
            get {
                return ResourceManager.GetString("___Cycle_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic mode is not allowed while any control key is in Service mode!.
        /// </summary>
        public static string ___Cyclic_mode_is_not_allowed_while_any_control_key_is_in_Service_mode___ {
            get {
                return ResourceManager.GetString("___Cyclic_mode_is_not_allowed_while_any_control_key_is_in_Service_mode___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadman.
        /// </summary>
        public static string ___Deadman__ {
            get {
                return ResourceManager.GetString("___Deadman__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door circuit .
        /// </summary>
        public static string ___Door_circuit___ {
            get {
                return ResourceManager.GetString("___Door_circuit___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors closed.
        /// </summary>
        public static string ___Doors_closed__ {
            get {
                return ResourceManager.GetString("___Doors_closed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors locked.
        /// </summary>
        public static string ___Doors_locked__ {
            get {
                return ResourceManager.GetString("___Doors_locked__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop.
        /// </summary>
        public static string ___Emergency_stop__ {
            get {
                return ResourceManager.GetString("___Emergency_stop__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Stop .
        /// </summary>
        public static string ___Emergency_Stop___ {
            get {
                return ResourceManager.GetString("___Emergency_Stop___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop active.
        /// </summary>
        public static string ___Emergency_stop_active__ {
            get {
                return ResourceManager.GetString("___Emergency_stop_active__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop active: Unlocking doors!.
        /// </summary>
        public static string ___Emergency_stop_active__Unlocking_doors___ {
            get {
                return ResourceManager.GetString("___Emergency_stop_active__Unlocking_doors___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string ___Empty__ {
            get {
                return ResourceManager.GetString("___Empty__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy saving mode - Inactivity time.
        /// </summary>
        public static string ___Energy_saving_mode___Inactivity_time__ {
            get {
                return ResourceManager.GetString("___Energy_saving_mode___Inactivity_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity header.
        /// </summary>
        public static string ___Entity_header__ {
            get {
                return ResourceManager.GetString("___Entity_header__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ___Error__ {
            get {
                return ResourceManager.GetString("___Error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force step mode..
        /// </summary>
        public static string ___Force_step_mode___ {
            get {
                return ResourceManager.GetString("___Force_step_mode___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded tag .
        /// </summary>
        public static string ___Founded_tag___ {
            get {
                return ResourceManager.GetString("___Founded_tag___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global control voltage.
        /// </summary>
        public static string ___Global_control_voltage__ {
            get {
                return ResourceManager.GetString("___Global_control_voltage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global control voltage interrupted: Unlocking doors!.
        /// </summary>
        public static string ___Global_control_voltage_interrupted__Unlocking_doors___ {
            get {
                return ResourceManager.GetString("___Global_control_voltage_interrupted__Unlocking_doors___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global votage.
        /// </summary>
        public static string ___Global_votage__ {
            get {
                return ResourceManager.GetString("___Global_votage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUND.
        /// </summary>
        public static string ___GROUND__ {
            get {
                return ResourceManager.GetString("___GROUND__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUND ALL.
        /// </summary>
        public static string ___GROUND_ALL__ {
            get {
                return ResourceManager.GetString("___GROUND_ALL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground task.
        /// </summary>
        public static string ___Ground_task__ {
            get {
                return ResourceManager.GetString("___Ground_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grounded.
        /// </summary>
        public static string ___Grounded__ {
            get {
                return ResourceManager.GetString("___Grounded__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grounding mode has been done..
        /// </summary>
        public static string ___Grounding_mode_has_been_done___ {
            get {
                return ResourceManager.GetString("___Grounding_mode_has_been_done___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grounding mode has been invoked..
        /// </summary>
        public static string ___Grounding_mode_has_been_invoked___ {
            get {
                return ResourceManager.GetString("___Grounding_mode_has_been_invoked___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string ___Group__ {
            get {
                return ResourceManager.GetString("___Group__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart beat.
        /// </summary>
        public static string ___Heart_beat__ {
            get {
                return ResourceManager.GetString("___Heart_beat__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holding process.
        /// </summary>
        public static string ___Holding_process__ {
            get {
                return ResourceManager.GetString("___Holding_process__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDLE.
        /// </summary>
        public static string ___IDLE__ {
            get {
                return ResourceManager.GetString("___IDLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In automatic.
        /// </summary>
        public static string ___In_automatic__ {
            get {
                return ResourceManager.GetString("___In_automatic__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Inactive or Manual or Grounded.
        /// </summary>
        public static string ___In_Inactive_or_Manual_or_Grounded__ {
            get {
                return ResourceManager.GetString("___In_Inactive_or_Manual_or_Grounded__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In manual.
        /// </summary>
        public static string ___In_manual__ {
            get {
                return ResourceManager.GetString("___In_manual__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In step mode.
        /// </summary>
        public static string ___In_step_mode__ {
            get {
                return ResourceManager.GetString("___In_step_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke restore sequences on each stations..
        /// </summary>
        public static string ___Invoke_restore_sequences_on_each_stations___ {
            get {
                return ResourceManager.GetString("___Invoke_restore_sequences_on_each_stations___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke suspend sequences on each stations..
        /// </summary>
        public static string ___Invoke_suspend_sequences_on_each_stations___ {
            get {
                return ResourceManager.GetString("___Invoke_suspend_sequences_on_each_stations___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is grounding.
        /// </summary>
        public static string ___Is_grounding__ {
            get {
                return ResourceManager.GetString("___Is_grounding__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Auto task.
        /// </summary>
        public static string ___Key_Auto_task__ {
            get {
                return ResourceManager.GetString("___Key_Auto_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Manual task.
        /// </summary>
        public static string ___Key_Manual_task__ {
            get {
                return ResourceManager.GetString("___Key_Manual_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key service task.
        /// </summary>
        public static string ___Key_service_task__ {
            get {
                return ResourceManager.GetString("___Key_service_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key state.
        /// </summary>
        public static string ___Key_state__ {
            get {
                return ResourceManager.GetString("___Key_state__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Step task.
        /// </summary>
        public static string ___Key_Step_task__ {
            get {
                return ResourceManager.GetString("___Key_Step_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key UID.
        /// </summary>
        public static string ___Key_UID__ {
            get {
                return ResourceManager.GetString("___Key_UID__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyState1.
        /// </summary>
        public static string ___KeyState1__ {
            get {
                return ResourceManager.GetString("___KeyState1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyState2.
        /// </summary>
        public static string ___KeyState2__ {
            get {
                return ResourceManager.GetString("___KeyState2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Rework Name.
        /// </summary>
        public static string ___Last_Rework_Name__ {
            get {
                return ResourceManager.GetString("___Last_Rework_Name__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last station.
        /// </summary>
        public static string ___Last_station__ {
            get {
                return ResourceManager.GetString("___Last_station__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light curtain.
        /// </summary>
        public static string ___Light_curtain__ {
            get {
                return ResourceManager.GetString("___Light_curtain__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local control voltage.
        /// </summary>
        public static string ___Local_control_voltage__ {
            get {
                return ResourceManager.GetString("___Local_control_voltage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local door voltage.
        /// </summary>
        public static string ___Local_door_voltage__ {
            get {
                return ResourceManager.GetString("___Local_door_voltage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Doors.
        /// </summary>
        public static string ___Local_Doors__ {
            get {
                return ResourceManager.GetString("___Local_Doors__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local voltage.
        /// </summary>
        public static string ___Local_voltage__ {
            get {
                return ResourceManager.GetString("___Local_voltage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local voltage interrupted: Unlocking doors!.
        /// </summary>
        public static string ___Local_voltage_interrupted__Unlocking_doors___ {
            get {
                return ResourceManager.GetString("___Local_voltage_interrupted__Unlocking_doors___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string ___Lock__ {
            get {
                return ResourceManager.GetString("___Lock__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string ___Locked__ {
            get {
                return ResourceManager.GetString("___Locked__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUAL.
        /// </summary>
        public static string ___MANUAL__ {
            get {
                return ResourceManager.GetString("___MANUAL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual mode is not possibe to set(At least one SERVICE and one MANUAL keys must be in position!).
        /// </summary>
        public static string ___Manual_mode_is_not_possibe_to_set_At_least_one_SERVICE_and_one_MANUAL_keys_must_be_in_position____ {
            get {
                return ResourceManager.GetString("___Manual_mode_is_not_possibe_to_set_At_least_one_SERVICE_and_one_MANUAL_keys_mus" +
                        "t_be_in_position____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual mode is starting.
        /// </summary>
        public static string ___Manual_mode_is_starting__ {
            get {
                return ResourceManager.GetString("___Manual_mode_is_starting__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual mode is starting due service key combination (Manual / Service).
        /// </summary>
        public static string ___Manual_mode_is_starting_due_service_key_combination__Manual___Service___ {
            get {
                return ResourceManager.GetString("___Manual_mode_is_starting_due_service_key_combination__Manual___Service___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string ___Master__ {
            get {
                return ResourceManager.GetString("___Master__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max allowed number of any recurring failures (consecutive).
        /// </summary>
        public static string ___Max_allowed_number_of_any_recurring_failures__consecutive___ {
            get {
                return ResourceManager.GetString("___Max_allowed_number_of_any_recurring_failures__consecutive___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max allowed number of same recurring failures (consecutive).
        /// </summary>
        public static string ___Max_allowed_number_of_same_recurring_failures__consecutive___ {
            get {
                return ResourceManager.GetString("___Max_allowed_number_of_same_recurring_failures__consecutive___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing link to control panel components (Buttons, Mode Keys, Normal/Service)! No function is being executed!.
        /// </summary>
        public static string ___Missing_link_to_control_panel_components__Buttons__Mode_Keys__Normal_Service___No_function_is_being_executed___ {
            get {
                return ResourceManager.GetString("___Missing_link_to_control_panel_components__Buttons__Mode_Keys__Normal_Service__" +
                        "_No_function_is_being_executed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing link to Controlled unit! No function is being executed!.
        /// </summary>
        public static string ___Missing_link_to_Controlled_unit__No_function_is_being_executed___ {
            get {
                return ResourceManager.GetString("___Missing_link_to_Controlled_unit__No_function_is_being_executed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode key .
        /// </summary>
        public static string ___Mode_key___ {
            get {
                return ResourceManager.GetString("___Mode_key___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode keys are not in correct position..
        /// </summary>
        public static string ___Mode_keys_are_not_in_correct_position___ {
            get {
                return ResourceManager.GetString("___Mode_keys_are_not_in_correct_position___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string ___Modified__ {
            get {
                return ResourceManager.GetString("___Modified__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next on Failed.
        /// </summary>
        public static string ___Next_on_Failed__ {
            get {
                return ResourceManager.GetString("___Next_on_Failed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next on Passed.
        /// </summary>
        public static string ___Next_on_Passed__ {
            get {
                return ResourceManager.GetString("___Next_on_Passed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next station.
        /// </summary>
        public static string ___Next_station__ {
            get {
                return ResourceManager.GetString("___Next_station__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal.
        /// </summary>
        public static string ___Nominal__ {
            get {
                return ResourceManager.GetString("___Nominal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string ___Normal__ {
            get {
                return ResourceManager.GetString("___Normal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal/Service key .
        /// </summary>
        public static string ___Normal_Service_key___ {
            get {
                return ResourceManager.GetString("___Normal_Service_key___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened.
        /// </summary>
        public static string ___Opened__ {
            get {
                return ResourceManager.GetString("___Opened__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation ended.
        /// </summary>
        public static string ___Operation_ended__ {
            get {
                return ResourceManager.GetString("___Operation_ended__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation started.
        /// </summary>
        public static string ___Operation_started__ {
            get {
                return ResourceManager.GetString("___Operation_started__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations opened.
        /// </summary>
        public static string ___Operations_opened__ {
            get {
                return ResourceManager.GetString("___Operations_opened__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAIR TAG WITH ASSIGNED VALUE EXAMPLE.
        /// </summary>
        public static string ___PAIR_TAG_WITH_ASSIGNED_VALUE_EXAMPLE__ {
            get {
                return ResourceManager.GetString("___PAIR_TAG_WITH_ASSIGNED_VALUE_EXAMPLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing Tag.
        /// </summary>
        public static string ___Pairing_Tag__ {
            get {
                return ResourceManager.GetString("___Pairing_Tag__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Position.
        /// </summary>
        public static string ___Pick_Position__ {
            get {
                return ResourceManager.GetString("___Pick_Position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place  Position.
        /// </summary>
        public static string ___Place__Position__ {
            get {
                return ResourceManager.GetString("___Place__Position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please acknowledge recurring failure!.
        /// </summary>
        public static string ___Please_acknowledge_recurring_failure___ {
            get {
                return ResourceManager.GetString("___Please_acknowledge_recurring_failure___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please acknowledge recurring failure! .
        /// </summary>
        public static string ___Please_acknowledge_recurring_failure____ {
            get {
                return ResourceManager.GetString("___Please_acknowledge_recurring_failure____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presure OK .
        /// </summary>
        public static string ___Presure_OK___ {
            get {
                return ResourceManager.GetString("___Presure_OK___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process data.
        /// </summary>
        public static string ___Process_data__ {
            get {
                return ResourceManager.GetString("___Process_data__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process data not selected.
        /// </summary>
        public static string ___Process_data_not_selected__ {
            get {
                return ResourceManager.GetString("___Process_data_not_selected__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production planer.
        /// </summary>
        public static string ___Production_planer__ {
            get {
                return ResourceManager.GetString("___Production_planer__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production planer completed required plan! .
        /// </summary>
        public static string ___Production_planer_completed_required_plan____ {
            get {
                return ResourceManager.GetString("___Production_planer_completed_required_plan____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production planer is empty! .
        /// </summary>
        public static string ___Production_planer_is_empty____ {
            get {
                return ResourceManager.GetString("___Production_planer_is_empty____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READY TO START.
        /// </summary>
        public static string ___READY_TO_START__ {
            get {
                return ResourceManager.GetString("___READY_TO_START__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        public static string ___Recipe__ {
            get {
                return ResourceManager.GetString("___Recipe__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe created.
        /// </summary>
        public static string ___Recipe_created__ {
            get {
                return ResourceManager.GetString("___Recipe_created__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe modified.
        /// </summary>
        public static string ___Recipe_modified__ {
            get {
                return ResourceManager.GetString("___Recipe_modified__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string ___Recover__ {
            get {
                return ResourceManager.GetString("___Recover__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOVER ANY COMPONENTS.
        /// </summary>
        public static string ___RECOVER_ANY_COMPONENTS__ {
            get {
                return ResourceManager.GetString("___RECOVER_ANY_COMPONENTS__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOVER PROCESS.
        /// </summary>
        public static string ___RECOVER_PROCESS__ {
            get {
                return ResourceManager.GetString("___RECOVER_PROCESS__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover task.
        /// </summary>
        public static string ___Recover_task__ {
            get {
                return ResourceManager.GetString("___Recover_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover task has been done..
        /// </summary>
        public static string ___Recover_task_has_been_done___ {
            get {
                return ResourceManager.GetString("___Recover_task_has_been_done___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovered.
        /// </summary>
        public static string ___Recovered__ {
            get {
                return ResourceManager.GetString("___Recovered__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ___Reset__ {
            get {
                return ResourceManager.GetString("___Reset__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ___Results__ {
            get {
                return ResourceManager.GetString("___Results__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rework Count.
        /// </summary>
        public static string ___Rework_Count__ {
            get {
                return ResourceManager.GetString("___Rework_Count__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reworked.
        /// </summary>
        public static string ___Reworked__ {
            get {
                return ResourceManager.GetString("___Reworked__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety doors OK.
        /// </summary>
        public static string ___Safety_doors_OK__ {
            get {
                return ResourceManager.GetString("___Safety_doors_OK__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string ___Service__ {
            get {
                return ResourceManager.GetString("___Service__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting step mode!.
        /// </summary>
        public static string ___Setting_step_mode___ {
            get {
                return ResourceManager.GetString("___Setting_step_mode___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Cyclic or Step mode. It depends on key position.
        /// </summary>
        public static string ___Setup_Cyclic_or_Step_mode__It_depends_on_key_position__ {
            get {
                return ResourceManager.GetString("___Setup_Cyclic_or_Step_mode__It_depends_on_key_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard door.
        /// </summary>
        public static string ___Standard_door__ {
            get {
                return ResourceManager.GetString("___Standard_door__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start manual/Service mode.
        /// </summary>
        public static string ___Start_manual_Service_mode__ {
            get {
                return ResourceManager.GetString("___Start_manual_Service_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START MEASURE CT TRIGGER.
        /// </summary>
        public static string ___START_MEASURE_CT_TRIGGER__ {
            get {
                return ResourceManager.GetString("___START_MEASURE_CT_TRIGGER__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts automatic sequence. Before start you need to perform grounding sequence..
        /// </summary>
        public static string ___Starts_automatic_sequence__Before_start_you_need_to_perform_grounding_sequence___ {
            get {
                return ResourceManager.GetString("___Starts_automatic_sequence__Before_start_you_need_to_perform_grounding_sequence" +
                        "___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts suspend sequence of process(automatic,ground sequence). .
        /// </summary>
        public static string ___Starts_suspend_sequence_of_process_automatic_ground_sequence_____ {
            get {
                return ResourceManager.GetString("___Starts_suspend_sequence_of_process_automatic_ground_sequence_____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ___Status__ {
            get {
                return ResourceManager.GetString("___Status__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS INFO.
        /// </summary>
        public static string ___STATUS_INFO__ {
            get {
                return ResourceManager.GetString("___STATUS_INFO__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step mode.
        /// </summary>
        public static string ___Step_mode__ {
            get {
                return ResourceManager.GetString("___Step_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step mode is required because Service key position is set!.
        /// </summary>
        public static string ___Step_mode_is_required_because_Service_key_position_is_set___ {
            get {
                return ResourceManager.GetString("___Step_mode_is_required_because_Service_key_position_is_set___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step mode is required but mode key is not in required position!.
        /// </summary>
        public static string ___Step_mode_is_required_but_mode_key_is_not_in_required_position___ {
            get {
                return ResourceManager.GetString("___Step_mode_is_required_but_mode_key_is_not_in_required_position___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step mode is set or all are inactive!.
        /// </summary>
        public static string ___Step_mode_is_set_or_all_are_inactive___ {
            get {
                return ResourceManager.GetString("___Step_mode_is_set_or_all_are_inactive___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step time.
        /// </summary>
        public static string ___Step_time__ {
            get {
                return ResourceManager.GetString("___Step_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string ___Suspend__ {
            get {
                return ResourceManager.GetString("___Suspend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUSPEND PROCESS.
        /// </summary>
        public static string ___SUSPEND_PROCESS__ {
            get {
                return ResourceManager.GetString("___SUSPEND_PROCESS__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend task.
        /// </summary>
        public static string ___Suspend_task__ {
            get {
                return ResourceManager.GetString("___Suspend_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend task has been done..
        /// </summary>
        public static string ___Suspend_task_has_been_done___ {
            get {
                return ResourceManager.GetString("___Suspend_task_has_been_done___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string ___Suspended__ {
            get {
                return ResourceManager.GetString("___Suspended__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUSPENDING COMPONENTS.
        /// </summary>
        public static string ___SUSPENDING_COMPONENTS__ {
            get {
                return ResourceManager.GetString("___SUSPENDING_COMPONENTS__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag .
        /// </summary>
        public static string ___Tag___ {
            get {
                return ResourceManager.GetString("___Tag___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Components.
        /// </summary>
        public static string ___Technology_Components__ {
            get {
                return ResourceManager.GetString("___Technology_Components__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology data.
        /// </summary>
        public static string ___Technology_data__ {
            get {
                return ResourceManager.GetString("___Technology_data__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test multi positions.
        /// </summary>
        public static string ___Test_multi_positions__ {
            get {
                return ResourceManager.GetString("___Test_multi_positions__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test positions.
        /// </summary>
        public static string ___Test_positions__ {
            get {
                return ResourceManager.GetString("___Test_positions__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.
        /// </summary>
        public static string ___Unlocked__ {
            get {
                return ResourceManager.GetString("___Unlocked__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage is Off!.
        /// </summary>
        public static string ___Voltage_is_Off___ {
            get {
                return ResourceManager.GetString("___Voltage_is_Off___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAITING FOR START.
        /// </summary>
        public static string ___WAITING_FOR_START__ {
            get {
                return ResourceManager.GetString("___WAITING_FOR_START__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to close and lock  all doors!.
        /// </summary>
        public static string ___Waiting_to_close_and_lock__all_doors___ {
            get {
                return ResourceManager.GetString("___Waiting_to_close_and_lock__all_doors___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to release recover button.
        /// </summary>
        public static string ___Waiting_to_release_recover_button__ {
            get {
                return ResourceManager.GetString("___Waiting_to_release_recover_button__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to release suspend button.
        /// </summary>
        public static string ___Waiting_to_release_suspend_button__ {
            get {
                return ResourceManager.GetString("___Waiting_to_release_suspend_button__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to unlock  all doors!.
        /// </summary>
        public static string ___Waiting_to_unlock__all_doors___ {
            get {
                return ResourceManager.GetString("___Waiting_to_unlock__all_doors___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ___Warning__ {
            get {
                return ResourceManager.GetString("___Warning__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to load default settings?.
        /// </summary>
        public static string ___Would_you_like_to_load_default_settings___ {
            get {
                return ResourceManager.GetString("___Would_you_like_to_load_default_settings___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone .
        /// </summary>
        public static string ___Zone___ {
            get {
                return ResourceManager.GetString("___Zone___", resourceCulture);
            }
        }
    }
}
