//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace x_template_xPlcConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("x_template_xPlcConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Consecutive failure) The number of any recurring failure count has been reached!.
        /// </summary>
        public static string ____Consecutive_failure__The_number_of_any_recurring_failure_count_has_been_reached___ {
            get {
                return ResourceManager.GetString("____Consecutive_failure__The_number_of_any_recurring_failure_count_has_been_reach" +
                        "ed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Consecutive failure) The number of same recurring failure count has been reached!.
        /// </summary>
        public static string ____Consecutive_failure__The_number_of_same_recurring_failure_count_has_been_reached___ {
            get {
                return ResourceManager.GetString("____Consecutive_failure__The_number_of_same_recurring_failure_count_has_been_reac" +
                        "hed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _cu00x.
        /// </summary>
        public static string ____cu00x__ {
            get {
                return ResourceManager.GetString("____cu00x__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW TAG  EXAMPLE.
        /// </summary>
        public static string ___ADD_NEW_TAG__EXAMPLE__ {
            get {
                return ResourceManager.GetString("___ADD_NEW_TAG__EXAMPLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Tag.
        /// </summary>
        public static string ___Adding_Tag__ {
            get {
                return ResourceManager.GetString("___Adding_Tag__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air pressure.
        /// </summary>
        public static string ___Air_pressure__ {
            get {
                return ResourceManager.GetString("___Air_pressure__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air pressure is not sufficient!.
        /// </summary>
        public static string ___Air_pressure_is_not_sufficient___ {
            get {
                return ResourceManager.GetString("___Air_pressure_is_not_sufficient___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ___All__ {
            get {
                return ResourceManager.GetString("___All__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All keys in automatic.
        /// </summary>
        public static string ___All_keys_in_automatic__ {
            get {
                return ResourceManager.GetString("___All_keys_in_automatic__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All keys in normal.
        /// </summary>
        public static string ___All_keys_in_normal__ {
            get {
                return ResourceManager.GetString("___All_keys_in_normal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exist!.
        /// </summary>
        public static string ___already_exist___ {
            get {
                return ResourceManager.GetString("___already_exist___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string ___Answer__ {
            get {
                return ResourceManager.GetString("___Answer__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any button.
        /// </summary>
        public static string ___Any_button__ {
            get {
                return ResourceManager.GetString("___Any_button__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any key in manual.
        /// </summary>
        public static string ___Any_key_in_manual__ {
            get {
                return ResourceManager.GetString("___Any_key_in_manual__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any key in service.
        /// </summary>
        public static string ___Any_key_in_service__ {
            get {
                return ResourceManager.GetString("___Any_key_in_service__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any key in step.
        /// </summary>
        public static string ___Any_key_in_step__ {
            get {
                return ResourceManager.GetString("___Any_key_in_step__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any present.
        /// </summary>
        public static string ___Any_present__ {
            get {
                return ResourceManager.GetString("___Any_present__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any station in automatic mode.
        /// </summary>
        public static string ___Any_station_in_automatic_mode__ {
            get {
                return ResourceManager.GetString("___Any_station_in_automatic_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any station in manual mode.
        /// </summary>
        public static string ___Any_station_in_manual_mode__ {
            get {
                return ResourceManager.GetString("___Any_station_in_manual_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any station in step mode.
        /// </summary>
        public static string ___Any_station_in_step_mode__ {
            get {
                return ResourceManager.GetString("___Any_station_in_step_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any station is grounding.
        /// </summary>
        public static string ___Any_station_is_grounding__ {
            get {
                return ResourceManager.GetString("___Any_station_is_grounding__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any station is holded.
        /// </summary>
        public static string ___Any_station_is_holded__ {
            get {
                return ResourceManager.GetString("___Any_station_is_holded__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Value.
        /// </summary>
        public static string ___Assigned_Value__ {
            get {
                return ResourceManager.GetString("___Assigned_Value__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autmatic mode allowed.
        /// </summary>
        public static string ___Autmatic_mode_allowed__ {
            get {
                return ResourceManager.GetString("___Autmatic_mode_allowed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string ___Auto__ {
            get {
                return ResourceManager.GetString("___Auto__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMAT.
        /// </summary>
        public static string ___AUTOMAT__ {
            get {
                return ResourceManager.GetString("___AUTOMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMAT ALL.
        /// </summary>
        public static string ___AUTOMAT_ALL__ {
            get {
                return ResourceManager.GetString("___AUTOMAT_ALL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automat mode has been done..
        /// </summary>
        public static string ___Automat_mode_has_been_done___ {
            get {
                return ResourceManager.GetString("___Automat_mode_has_been_done___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automat mode has been invoked..
        /// </summary>
        public static string ___Automat_mode_has_been_invoked___ {
            get {
                return ResourceManager.GetString("___Automat_mode_has_been_invoked___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automat task.
        /// </summary>
        public static string ___Automat_task__ {
            get {
                return ResourceManager.GetString("___Automat_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string ___Automatic__ {
            get {
                return ResourceManager.GetString("___Automatic__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic mode is not possibe to set(All keys must be in NORMAL and AUTO!).
        /// </summary>
        public static string ___Automatic_mode_is_not_possibe_to_set_All_keys_must_be_in_NORMAL_and_AUTO____ {
            get {
                return ResourceManager.GetString("___Automatic_mode_is_not_possibe_to_set_All_keys_must_be_in_NORMAL_and_AUTO____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic mode is set(Step mode is disabled)!.
        /// </summary>
        public static string ___Automatic_mode_is_set_Step_mode_is_disabled____ {
            get {
                return ResourceManager.GetString("___Automatic_mode_is_set_Step_mode_is_disabled____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average clean cycle time.
        /// </summary>
        public static string ___Average_clean_cycle_time__ {
            get {
                return ResourceManager.GetString("___Average_clean_cycle_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average cycle time.
        /// </summary>
        public static string ___Average_cycle_time__ {
            get {
                return ResourceManager.GetString("___Average_cycle_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average cycle time filter constant.
        /// </summary>
        public static string ___Average_cycle_time_filter_constant__ {
            get {
                return ResourceManager.GetString("___Average_cycle_time_filter_constant__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic door.
        /// </summary>
        public static string ___Basic_door__ {
            get {
                return ResourceManager.GetString("___Basic_door__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEZPECNOST ZARIADENIA NARUSENA. NIEJE MOZNE VYKONAT AKCIU.
        /// </summary>
        public static string ___BEZPECNOST_ZARIADENIA_NARUSENA__NIEJE_MOZNE_VYKONAT_AKCIU__ {
            get {
                return ResourceManager.GetString("___BEZPECNOST_ZARIADENIA_NARUSENA__NIEJE_MOZNE_VYKONAT_AKCIU__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink period.
        /// </summary>
        public static string ___Blink_period__ {
            get {
                return ResourceManager.GetString("___Blink_period__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brings the device into basic position..
        /// </summary>
        public static string ___Brings_the_device_into_basic_position___ {
            get {
                return ResourceManager.GetString("___Brings_the_device_into_basic_position___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonAuto.
        /// </summary>
        public static string ___ButtonAuto__ {
            get {
                return ResourceManager.GetString("___ButtonAuto__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonAutoLight.
        /// </summary>
        public static string ___ButtonAutoLight__ {
            get {
                return ResourceManager.GetString("___ButtonAutoLight__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonGround.
        /// </summary>
        public static string ___ButtonGround__ {
            get {
                return ResourceManager.GetString("___ButtonGround__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonGroundLight.
        /// </summary>
        public static string ___ButtonGroundLight__ {
            get {
                return ResourceManager.GetString("___ButtonGroundLight__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonRecover.
        /// </summary>
        public static string ___ButtonRecover__ {
            get {
                return ResourceManager.GetString("___ButtonRecover__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonStartLight.
        /// </summary>
        public static string ___ButtonStartLight__ {
            get {
                return ResourceManager.GetString("___ButtonStartLight__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonStopLight.
        /// </summary>
        public static string ___ButtonStopLight__ {
            get {
                return ResourceManager.GetString("___ButtonStopLight__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonSuspend.
        /// </summary>
        public static string ___ButtonSuspend__ {
            get {
                return ResourceManager.GetString("___ButtonSuspend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAKANIE NA OBSLUHU PALETIZERA - ZAVRITE DVERE!.
        /// </summary>
        public static string ___CAKANIE_NA_OBSLUHU_PALETIZERA___ZAVRITE_DVERE___ {
            get {
                return ResourceManager.GetString("___CAKANIE_NA_OBSLUHU_PALETIZERA___ZAVRITE_DVERE___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        public static string ___Carrier__ {
            get {
                return ResourceManager.GetString("___Carrier__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check general condition to recover zone (ControlVoltage, EStops, Presure...)!.
        /// </summary>
        public static string ___Check_general_condition_to_recover_zone__ControlVoltage__EStops__Presure_______ {
            get {
                return ResourceManager.GetString("___Check_general_condition_to_recover_zone__ControlVoltage__EStops__Presure______" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check general condition to suspned zone (ControlVoltage,EStops,Presure...)!.
        /// </summary>
        public static string ___Check_general_condition_to_suspned_zone__ControlVoltage_EStops_Presure_______ {
            get {
                return ResourceManager.GetString("___Check_general_condition_to_suspned_zone__ControlVoltage_EStops_Presure_______", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean loop time.
        /// </summary>
        public static string ___Clean_loop_time__ {
            get {
                return ResourceManager.GetString("___Clean_loop_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear step mode.
        /// </summary>
        public static string ___Clear_step_mode__ {
            get {
                return ResourceManager.GetString("___Clear_step_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ___Closed__ {
            get {
                return ResourceManager.GetString("___Closed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string ___Components__ {
            get {
                return ResourceManager.GetString("___Components__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string ___Config__ {
            get {
                return ResourceManager.GetString("___Config__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string ___Control__ {
            get {
                return ResourceManager.GetString("___Control__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Buttons.
        /// </summary>
        public static string ___Control_Buttons__ {
            get {
                return ResourceManager.GetString("___Control_Buttons__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel.
        /// </summary>
        public static string ___Control_panel__ {
            get {
                return ResourceManager.GetString("___Control_panel__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control voltage.
        /// </summary>
        public static string ___Control_voltage__ {
            get {
                return ResourceManager.GetString("___Control_voltage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ___Created__ {
            get {
                return ResourceManager.GetString("___Created__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CU00x.
        /// </summary>
        public static string ___CU00x__ {
            get {
                return ResourceManager.GetString("___CU00x__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle time.
        /// </summary>
        public static string ___Cycle_time__ {
            get {
                return ResourceManager.GetString("___Cycle_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic mode is not allowed while any control key is in Service mode!.
        /// </summary>
        public static string ___Cyclic_mode_is_not_allowed_while_any_control_key_is_in_Service_mode___ {
            get {
                return ResourceManager.GetString("___Cyclic_mode_is_not_allowed_while_any_control_key_is_in_Service_mode___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadman.
        /// </summary>
        public static string ___Deadman__ {
            get {
                return ResourceManager.GetString("___Deadman__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door circuit.
        /// </summary>
        public static string ___Door_circuit__ {
            get {
                return ResourceManager.GetString("___Door_circuit__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors closed.
        /// </summary>
        public static string ___Doors_closed__ {
            get {
                return ResourceManager.GetString("___Doors_closed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors locked.
        /// </summary>
        public static string ___Doors_locked__ {
            get {
                return ResourceManager.GetString("___Doors_locked__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop.
        /// </summary>
        public static string ___Emergency_stop__ {
            get {
                return ResourceManager.GetString("___Emergency_stop__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop active.
        /// </summary>
        public static string ___Emergency_stop_active__ {
            get {
                return ResourceManager.GetString("___Emergency_stop_active__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop active: Unlocking doors!.
        /// </summary>
        public static string ___Emergency_stop_active__Unlocking_doors___ {
            get {
                return ResourceManager.GetString("___Emergency_stop_active__Unlocking_doors___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string ___Empty__ {
            get {
                return ResourceManager.GetString("___Empty__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy saving mode - Inactivity time.
        /// </summary>
        public static string ___Energy_saving_mode___Inactivity_time__ {
            get {
                return ResourceManager.GetString("___Energy_saving_mode___Inactivity_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity header.
        /// </summary>
        public static string ___Entity_header__ {
            get {
                return ResourceManager.GetString("___Entity_header__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ___Error__ {
            get {
                return ResourceManager.GetString("___Error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string ___Exclude__ {
            get {
                return ResourceManager.GetString("___Exclude__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force step mode..
        /// </summary>
        public static string ___Force_step_mode___ {
            get {
                return ResourceManager.GetString("___Force_step_mode___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded tag.
        /// </summary>
        public static string ___Founded_tag__ {
            get {
                return ResourceManager.GetString("___Founded_tag__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global control voltage.
        /// </summary>
        public static string ___Global_control_voltage__ {
            get {
                return ResourceManager.GetString("___Global_control_voltage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global control voltage interrupted: Unlocking doors!.
        /// </summary>
        public static string ___Global_control_voltage_interrupted__Unlocking_doors___ {
            get {
                return ResourceManager.GetString("___Global_control_voltage_interrupted__Unlocking_doors___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global votage.
        /// </summary>
        public static string ___Global_votage__ {
            get {
                return ResourceManager.GetString("___Global_votage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUND.
        /// </summary>
        public static string ___GROUND__ {
            get {
                return ResourceManager.GetString("___GROUND__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUND ALL.
        /// </summary>
        public static string ___GROUND_ALL__ {
            get {
                return ResourceManager.GetString("___GROUND_ALL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground task.
        /// </summary>
        public static string ___Ground_task__ {
            get {
                return ResourceManager.GetString("___Ground_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grounded.
        /// </summary>
        public static string ___Grounded__ {
            get {
                return ResourceManager.GetString("___Grounded__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grounding mode has been done..
        /// </summary>
        public static string ___Grounding_mode_has_been_done___ {
            get {
                return ResourceManager.GetString("___Grounding_mode_has_been_done___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grounding mode has been invoked..
        /// </summary>
        public static string ___Grounding_mode_has_been_invoked___ {
            get {
                return ResourceManager.GetString("___Grounding_mode_has_been_invoked___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string ___Group__ {
            get {
                return ResourceManager.GetString("___Group__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart beat.
        /// </summary>
        public static string ___Heart_beat__ {
            get {
                return ResourceManager.GetString("___Heart_beat__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holding process.
        /// </summary>
        public static string ___Holding_process__ {
            get {
                return ResourceManager.GetString("___Holding_process__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontalny prisun vstupnych blistrov.
        /// </summary>
        public static string ___Horizontalny_prisun_vstupnych_blistrov__ {
            get {
                return ResourceManager.GetString("___Horizontalny_prisun_vstupnych_blistrov__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontalny prisun vystupnych blistrov.
        /// </summary>
        public static string ___Horizontalny_prisun_vystupnych_blistrov__ {
            get {
                return ResourceManager.GetString("___Horizontalny_prisun_vystupnych_blistrov__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDLE.
        /// </summary>
        public static string ___IDLE__ {
            get {
                return ResourceManager.GetString("___IDLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In automatic.
        /// </summary>
        public static string ___In_automatic__ {
            get {
                return ResourceManager.GetString("___In_automatic__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Inactive or Manual or Grounded.
        /// </summary>
        public static string ___In_Inactive_or_Manual_or_Grounded__ {
            get {
                return ResourceManager.GetString("___In_Inactive_or_Manual_or_Grounded__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In manual.
        /// </summary>
        public static string ___In_manual__ {
            get {
                return ResourceManager.GetString("___In_manual__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In step mode.
        /// </summary>
        public static string ___In_step_mode__ {
            get {
                return ResourceManager.GetString("___In_step_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INIT.
        /// </summary>
        public static string ___INIT__ {
            get {
                return ResourceManager.GetString("___INIT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke restore sequences on each stations..
        /// </summary>
        public static string ___Invoke_restore_sequences_on_each_stations___ {
            get {
                return ResourceManager.GetString("___Invoke_restore_sequences_on_each_stations___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke suspend sequences on each stations..
        /// </summary>
        public static string ___Invoke_suspend_sequences_on_each_stations___ {
            get {
                return ResourceManager.GetString("___Invoke_suspend_sequences_on_each_stations___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is founded but assigned value is empty! Would you like continue?.
        /// </summary>
        public static string ___is_founded_but_assigned_value_is_empty__Would_you_like_continue___ {
            get {
                return ResourceManager.GetString("___is_founded_but_assigned_value_is_empty__Would_you_like_continue___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is grounding.
        /// </summary>
        public static string ___Is_grounding__ {
            get {
                return ResourceManager.GetString("___Is_grounding__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is inactive!.
        /// </summary>
        public static string ___is_inactive___ {
            get {
                return ResourceManager.GetString("___is_inactive___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not founded ! Would you like assign right now?.
        /// </summary>
        public static string ___is_not_founded___Would_you_like_assign_right_now___ {
            get {
                return ResourceManager.GetString("___is_not_founded___Would_you_like_assign_right_now___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not founded due collection is empty ! Would you like assign right now?.
        /// </summary>
        public static string ___is_not_founded_due_collection_is_empty___Would_you_like_assign_right_now___ {
            get {
                return ResourceManager.GetString("___is_not_founded_due_collection_is_empty___Would_you_like_assign_right_now___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Auto task.
        /// </summary>
        public static string ___Key_Auto_task__ {
            get {
                return ResourceManager.GetString("___Key_Auto_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Manual task.
        /// </summary>
        public static string ___Key_Manual_task__ {
            get {
                return ResourceManager.GetString("___Key_Manual_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key service task.
        /// </summary>
        public static string ___Key_service_task__ {
            get {
                return ResourceManager.GetString("___Key_service_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key state.
        /// </summary>
        public static string ___Key_state__ {
            get {
                return ResourceManager.GetString("___Key_state__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Step task.
        /// </summary>
        public static string ___Key_Step_task__ {
            get {
                return ResourceManager.GetString("___Key_Step_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key UID.
        /// </summary>
        public static string ___Key_UID__ {
            get {
                return ResourceManager.GetString("___Key_UID__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyState1.
        /// </summary>
        public static string ___KeyState1__ {
            get {
                return ResourceManager.GetString("___KeyState1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyState2.
        /// </summary>
        public static string ___KeyState2__ {
            get {
                return ResourceManager.GetString("___KeyState2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KONTROLA POCTU VSTUPNYCH BLISTROV.
        /// </summary>
        public static string ___KONTROLA_POCTU_VSTUPNYCH_BLISTROV__ {
            get {
                return ResourceManager.GetString("___KONTROLA_POCTU_VSTUPNYCH_BLISTROV__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KONTROLA PRITOMNOSTI SEPAROVANEHO KUSU.
        /// </summary>
        public static string ___KONTROLA_PRITOMNOSTI_SEPAROVANEHO_KUSU__ {
            get {
                return ResourceManager.GetString("___KONTROLA_PRITOMNOSTI_SEPAROVANEHO_KUSU__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Rework Name.
        /// </summary>
        public static string ___Last_Rework_Name__ {
            get {
                return ResourceManager.GetString("___Last_Rework_Name__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last station.
        /// </summary>
        public static string ___Last_station__ {
            get {
                return ResourceManager.GetString("___Last_station__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light curtain.
        /// </summary>
        public static string ___Light_curtain__ {
            get {
                return ResourceManager.GetString("___Light_curtain__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local control voltage.
        /// </summary>
        public static string ___Local_control_voltage__ {
            get {
                return ResourceManager.GetString("___Local_control_voltage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local door voltage.
        /// </summary>
        public static string ___Local_door_voltage__ {
            get {
                return ResourceManager.GetString("___Local_door_voltage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Doors.
        /// </summary>
        public static string ___Local_Doors__ {
            get {
                return ResourceManager.GetString("___Local_Doors__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local voltage.
        /// </summary>
        public static string ___Local_voltage__ {
            get {
                return ResourceManager.GetString("___Local_voltage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local voltage interrupted: Unlocking doors!.
        /// </summary>
        public static string ___Local_voltage_interrupted__Unlocking_doors___ {
            get {
                return ResourceManager.GetString("___Local_voltage_interrupted__Unlocking_doors___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string ___Lock__ {
            get {
                return ResourceManager.GetString("___Lock__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string ___Locked__ {
            get {
                return ResourceManager.GetString("___Locked__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUAL.
        /// </summary>
        public static string ___MANUAL__ {
            get {
                return ResourceManager.GetString("___MANUAL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual mode is not possibe to set(At least one SERVICE and one MANUAL keys must be in position!).
        /// </summary>
        public static string ___Manual_mode_is_not_possibe_to_set_At_least_one_SERVICE_and_one_MANUAL_keys_must_be_in_position____ {
            get {
                return ResourceManager.GetString("___Manual_mode_is_not_possibe_to_set_At_least_one_SERVICE_and_one_MANUAL_keys_mus" +
                        "t_be_in_position____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual mode is starting.
        /// </summary>
        public static string ___Manual_mode_is_starting__ {
            get {
                return ResourceManager.GetString("___Manual_mode_is_starting__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual mode is starting due service key combination (Manual / Service).
        /// </summary>
        public static string ___Manual_mode_is_starting_due_service_key_combination__Manual___Service___ {
            get {
                return ResourceManager.GetString("___Manual_mode_is_starting_due_service_key_combination__Manual___Service___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string ___Master__ {
            get {
                return ResourceManager.GetString("___Master__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max allowed number of any recurring failures (consecutive).
        /// </summary>
        public static string ___Max_allowed_number_of_any_recurring_failures__consecutive___ {
            get {
                return ResourceManager.GetString("___Max_allowed_number_of_any_recurring_failures__consecutive___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max allowed number of same recurring failures (consecutive).
        /// </summary>
        public static string ___Max_allowed_number_of_same_recurring_failures__consecutive___ {
            get {
                return ResourceManager.GetString("___Max_allowed_number_of_same_recurring_failures__consecutive___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing link to control panel components (Buttons, Mode Keys, Normal/Service)! No function is being executed!.
        /// </summary>
        public static string ___Missing_link_to_control_panel_components__Buttons__Mode_Keys__Normal_Service___No_function_is_being_executed___ {
            get {
                return ResourceManager.GetString("___Missing_link_to_control_panel_components__Buttons__Mode_Keys__Normal_Service__" +
                        "_No_function_is_being_executed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing link to Controlled unit! No function is being executed!.
        /// </summary>
        public static string ___Missing_link_to_Controlled_unit__No_function_is_being_executed___ {
            get {
                return ResourceManager.GetString("___Missing_link_to_Controlled_unit__No_function_is_being_executed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode key.
        /// </summary>
        public static string ___Mode_key__ {
            get {
                return ResourceManager.GetString("___Mode_key__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode keys are not in correct position..
        /// </summary>
        public static string ___Mode_keys_are_not_in_correct_position___ {
            get {
                return ResourceManager.GetString("___Mode_keys_are_not_in_correct_position___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string ___Modified__ {
            get {
                return ResourceManager.GetString("___Modified__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next on Failed.
        /// </summary>
        public static string ___Next_on_Failed__ {
            get {
                return ResourceManager.GetString("___Next_on_Failed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next on Passed.
        /// </summary>
        public static string ___Next_on_Passed__ {
            get {
                return ResourceManager.GetString("___Next_on_Passed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next station.
        /// </summary>
        public static string ___Next_station__ {
            get {
                return ResourceManager.GetString("___Next_station__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal.
        /// </summary>
        public static string ___Nominal__ {
            get {
                return ResourceManager.GetString("___Nominal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string ___Normal__ {
            get {
                return ResourceManager.GetString("___Normal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal/Service key.
        /// </summary>
        public static string ___Normal_Service_key__ {
            get {
                return ResourceManager.GetString("___Normal_Service_key__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oddelovanie blistrov na vstupe neaktive (P10)(P10.1)je nepritomne.
        /// </summary>
        public static string ___Oddelovanie_blistrov_na_vstupe_neaktive__P10__P10_1_je_nepritomne__ {
            get {
                return ResourceManager.GetString("___Oddelovanie_blistrov_na_vstupe_neaktive__P10__P10_1_je_nepritomne__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odelovac blistrov na vstupe.
        /// </summary>
        public static string ___Odelovac_blistrov_na_vstupe__ {
            get {
                return ResourceManager.GetString("___Odelovac_blistrov_na_vstupe__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened.
        /// </summary>
        public static string ___Opened__ {
            get {
                return ResourceManager.GetString("___Opened__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation ended.
        /// </summary>
        public static string ___Operation_ended__ {
            get {
                return ResourceManager.GetString("___Operation_ended__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation started.
        /// </summary>
        public static string ___Operation_started__ {
            get {
                return ResourceManager.GetString("___Operation_started__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations opened.
        /// </summary>
        public static string ___Operations_opened__ {
            get {
                return ResourceManager.GetString("___Operations_opened__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string ___Operator__ {
            get {
                return ResourceManager.GetString("___Operator__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAIR TAG WITH ASSIGNED VALUE EXAMPLE.
        /// </summary>
        public static string ___PAIR_TAG_WITH_ASSIGNED_VALUE_EXAMPLE__ {
            get {
                return ResourceManager.GetString("___PAIR_TAG_WITH_ASSIGNED_VALUE_EXAMPLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing Tag.
        /// </summary>
        public static string ___Pairing_Tag__ {
            get {
                return ResourceManager.GetString("___Pairing_Tag__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Position.
        /// </summary>
        public static string ___Pick_Position__ {
            get {
                return ResourceManager.GetString("___Pick_Position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place  Position.
        /// </summary>
        public static string ___Place__Position__ {
            get {
                return ResourceManager.GetString("___Place__Position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please acknowledge recurring failure!.
        /// </summary>
        public static string ___Please_acknowledge_recurring_failure___ {
            get {
                return ResourceManager.GetString("___Please_acknowledge_recurring_failure___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PODAVAC PLNY! ODSTRANTE PRAZDNE BLISTRE !.
        /// </summary>
        public static string ___PODAVAC_PLNY__ODSTRANTE_PRAZDNE_BLISTRE____ {
            get {
                return ResourceManager.GetString("___PODAVAC_PLNY__ODSTRANTE_PRAZDNE_BLISTRE____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PODAVAC PRAZDNY! DOPLNE BLISTRE !.
        /// </summary>
        public static string ___PODAVAC_PRAZDNY__DOPLNE_BLISTRE____ {
            get {
                return ResourceManager.GetString("___PODAVAC_PRAZDNY__DOPLNE_BLISTRE____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PODAVAC PRAZDNY! DOPLNE VSTUPNE BLISTRE !.
        /// </summary>
        public static string ___PODAVAC_PRAZDNY__DOPLNE_VSTUPNE_BLISTRE____ {
            get {
                return ResourceManager.GetString("___PODAVAC_PRAZDNY__DOPLNE_VSTUPNE_BLISTRE____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podopretie vstupneho blistra.
        /// </summary>
        public static string ___Podopretie_vstupneho_blistra__ {
            get {
                return ResourceManager.GetString("___Podopretie_vstupneho_blistra__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poziadavka novy blister.
        /// </summary>
        public static string ___Poziadavka_novy_blister__ {
            get {
                return ResourceManager.GetString("___Poziadavka_novy_blister__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poziadavka obsluhy vystupny buffer.
        /// </summary>
        public static string ___Poziadavka_obsluhy_vystupny_buffer__ {
            get {
                return ResourceManager.GetString("___Poziadavka_obsluhy_vystupny_buffer__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poziadavka vylozenie blistera.
        /// </summary>
        public static string ___Poziadavka_vylozenie_blistera__ {
            get {
                return ResourceManager.GetString("___Poziadavka_vylozenie_blistera__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presure OK.
        /// </summary>
        public static string ___Presure_OK__ {
            get {
                return ResourceManager.GetString("___Presure_OK__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisun vstupneho blistra.
        /// </summary>
        public static string ___Prisun_vstupneho_blistra__ {
            get {
                return ResourceManager.GetString("___Prisun_vstupneho_blistra__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pritomnost blistra v pracovnej pozicii.
        /// </summary>
        public static string ___Pritomnost_blistra_v_pracovnej_pozicii__ {
            get {
                return ResourceManager.GetString("___Pritomnost_blistra_v_pracovnej_pozicii__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pritomnost blistra v presuvaci.
        /// </summary>
        public static string ___Pritomnost_blistra_v_presuvaci__ {
            get {
                return ResourceManager.GetString("___Pritomnost_blistra_v_presuvaci__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pritomnost medzery medzi blistrami.
        /// </summary>
        public static string ___Pritomnost_medzery_medzi_blistrami__ {
            get {
                return ResourceManager.GetString("___Pritomnost_medzery_medzi_blistrami__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process data.
        /// </summary>
        public static string ___Process_data__ {
            get {
                return ResourceManager.GetString("___Process_data__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process data not selected.
        /// </summary>
        public static string ___Process_data_not_selected__ {
            get {
                return ResourceManager.GetString("___Process_data_not_selected__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production planer.
        /// </summary>
        public static string ___Production_planer__ {
            get {
                return ResourceManager.GetString("___Production_planer__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production planer completed required plan!.
        /// </summary>
        public static string ___Production_planer_completed_required_plan___ {
            get {
                return ResourceManager.GetString("___Production_planer_completed_required_plan___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production planer is empty!.
        /// </summary>
        public static string ___Production_planer_is_empty___ {
            get {
                return ResourceManager.GetString("___Production_planer_is_empty___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qantity.
        /// </summary>
        public static string ___Qantity__ {
            get {
                return ResourceManager.GetString("___Qantity__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READY TO START.
        /// </summary>
        public static string ___READY_TO_START__ {
            get {
                return ResourceManager.GetString("___READY_TO_START__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        public static string ___Recipe__ {
            get {
                return ResourceManager.GetString("___Recipe__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe created.
        /// </summary>
        public static string ___Recipe_created__ {
            get {
                return ResourceManager.GetString("___Recipe_created__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe modified.
        /// </summary>
        public static string ___Recipe_modified__ {
            get {
                return ResourceManager.GetString("___Recipe_modified__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string ___Recover__ {
            get {
                return ResourceManager.GetString("___Recover__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOVER ANY COMPONENTS.
        /// </summary>
        public static string ___RECOVER_ANY_COMPONENTS__ {
            get {
                return ResourceManager.GetString("___RECOVER_ANY_COMPONENTS__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOVER PROCESS.
        /// </summary>
        public static string ___RECOVER_PROCESS__ {
            get {
                return ResourceManager.GetString("___RECOVER_PROCESS__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover task.
        /// </summary>
        public static string ___Recover_task__ {
            get {
                return ResourceManager.GetString("___Recover_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover task has been done..
        /// </summary>
        public static string ___Recover_task_has_been_done___ {
            get {
                return ResourceManager.GetString("___Recover_task_has_been_done___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovered.
        /// </summary>
        public static string ___Recovered__ {
            get {
                return ResourceManager.GetString("___Recovered__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ___Reset__ {
            get {
                return ResourceManager.GetString("___Reset__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string ___Restore__ {
            get {
                return ResourceManager.GetString("___Restore__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ___Results__ {
            get {
                return ResourceManager.GetString("___Results__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rework Count.
        /// </summary>
        public static string ___Rework_Count__ {
            get {
                return ResourceManager.GetString("___Rework_Count__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reworked.
        /// </summary>
        public static string ___Reworked__ {
            get {
                return ResourceManager.GetString("___Reworked__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety doors OK.
        /// </summary>
        public static string ___Safety_doors_OK__ {
            get {
                return ResourceManager.GetString("___Safety_doors_OK__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPAROVANIE VSTUPNEHO BLISTRA - NPRESUNUTIE BLISTRA DO POZICIE NABERANIA.
        /// </summary>
        public static string ___SEPAROVANIE_VSTUPNEHO_BLISTRA___NPRESUNUTIE_BLISTRA_DO_POZICIE_NABERANIA__ {
            get {
                return ResourceManager.GetString("___SEPAROVANIE_VSTUPNEHO_BLISTRA___NPRESUNUTIE_BLISTRA_DO_POZICIE_NABERANIA__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPAROVANIE VSTUPNEHO BLISTRA - PRESUNUTIE BLISTRA DO POZICIE ODOBERANIA.
        /// </summary>
        public static string ___SEPAROVANIE_VSTUPNEHO_BLISTRA___PRESUNUTIE_BLISTRA_DO_POZICIE_ODOBERANIA__ {
            get {
                return ResourceManager.GetString("___SEPAROVANIE_VSTUPNEHO_BLISTRA___PRESUNUTIE_BLISTRA_DO_POZICIE_ODOBERANIA__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPAROVANIE VSTUPNEHO BLISTRA - SEPAROVANIE VYSUNUTE.
        /// </summary>
        public static string ___SEPAROVANIE_VSTUPNEHO_BLISTRA___SEPAROVANIE_VYSUNUTE__ {
            get {
                return ResourceManager.GetString("___SEPAROVANIE_VSTUPNEHO_BLISTRA___SEPAROVANIE_VYSUNUTE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPAROVANIE VSTUPNEHO BLISTRA - SEPAROVANIE ZASUNUTE.
        /// </summary>
        public static string ___SEPAROVANIE_VSTUPNEHO_BLISTRA___SEPAROVANIE_ZASUNUTE__ {
            get {
                return ResourceManager.GetString("___SEPAROVANIE_VSTUPNEHO_BLISTRA___SEPAROVANIE_ZASUNUTE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPAROVANIE VSTUPNEHO BLISTRA - UPEVENIE BLISTRA ZBOKU.
        /// </summary>
        public static string ___SEPAROVANIE_VSTUPNEHO_BLISTRA___UPEVENIE_BLISTRA_ZBOKU__ {
            get {
                return ResourceManager.GetString("___SEPAROVANIE_VSTUPNEHO_BLISTRA___UPEVENIE_BLISTRA_ZBOKU__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPAROVANIE VSTUPNEHO BLISTRA - VERTIKALNE VALCE VYSUNUTE.
        /// </summary>
        public static string ___SEPAROVANIE_VSTUPNEHO_BLISTRA___VERTIKALNE_VALCE_VYSUNUTE__ {
            get {
                return ResourceManager.GetString("___SEPAROVANIE_VSTUPNEHO_BLISTRA___VERTIKALNE_VALCE_VYSUNUTE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPAROVANIE VSTUPNEHO BLISTRA - VERTIKALNE VALCE ZASUNUT JEDEN.
        /// </summary>
        public static string ___SEPAROVANIE_VSTUPNEHO_BLISTRA___VERTIKALNE_VALCE_ZASUNUT_JEDEN__ {
            get {
                return ResourceManager.GetString("___SEPAROVANIE_VSTUPNEHO_BLISTRA___VERTIKALNE_VALCE_ZASUNUT_JEDEN__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPAROVANIE VSTUPNEHO BLISTRA - VERTIKALNE VALCE ZASUNUT OBIDVA.
        /// </summary>
        public static string ___SEPAROVANIE_VSTUPNEHO_BLISTRA___VERTIKALNE_VALCE_ZASUNUT_OBIDVA__ {
            get {
                return ResourceManager.GetString("___SEPAROVANIE_VSTUPNEHO_BLISTRA___VERTIKALNE_VALCE_ZASUNUT_OBIDVA__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPAROVANIE VSTUPNEHO BLISTRA - ZASUNUTE P4.
        /// </summary>
        public static string ___SEPAROVANIE_VSTUPNEHO_BLISTRA___ZASUNUTE_P4__ {
            get {
                return ResourceManager.GetString("___SEPAROVANIE_VSTUPNEHO_BLISTRA___ZASUNUTE_P4__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPAROVANIE VYSTUPNEHO BLISTRA - KONTROLA PRITOMNOSTI BLISTA NA SKLZE.
        /// </summary>
        public static string ___SEPAROVANIE_VYSTUPNEHO_BLISTRA___KONTROLA_PRITOMNOSTI_BLISTA_NA_SKLZE__ {
            get {
                return ResourceManager.GetString("___SEPAROVANIE_VYSTUPNEHO_BLISTRA___KONTROLA_PRITOMNOSTI_BLISTA_NA_SKLZE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPAROVANIE VYSTUPNEHO BLISTRA - UVOLNENIE BLISTRA.
        /// </summary>
        public static string ___SEPAROVANIE_VYSTUPNEHO_BLISTRA___UVOLNENIE_BLISTRA__ {
            get {
                return ResourceManager.GetString("___SEPAROVANIE_VYSTUPNEHO_BLISTRA___UVOLNENIE_BLISTRA__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPAROVANIE VYSTUPNEHO BLISTRA - ZASUNUTIE SUPPORTU.
        /// </summary>
        public static string ___SEPAROVANIE_VYSTUPNEHO_BLISTRA___ZASUNUTIE_SUPPORTU__ {
            get {
                return ResourceManager.GetString("___SEPAROVANIE_VYSTUPNEHO_BLISTRA___ZASUNUTIE_SUPPORTU__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string ___Service__ {
            get {
                return ResourceManager.GetString("___Service__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting step mode!.
        /// </summary>
        public static string ___Setting_step_mode___ {
            get {
                return ResourceManager.GetString("___Setting_step_mode___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Cyclic or Step mode. It depends on key position.
        /// </summary>
        public static string ___Setup_Cyclic_or_Step_mode__It_depends_on_key_position__ {
            get {
                return ResourceManager.GetString("___Setup_Cyclic_or_Step_mode__It_depends_on_key_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signalizacia upozornenia B.
        /// </summary>
        public static string ___Signalizacia_upozornenia_B__ {
            get {
                return ResourceManager.GetString("___Signalizacia_upozornenia_B__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signalizacia upozornenia G.
        /// </summary>
        public static string ___Signalizacia_upozornenia_G__ {
            get {
                return ResourceManager.GetString("___Signalizacia_upozornenia_G__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signalizacia upozornenia R.
        /// </summary>
        public static string ___Signalizacia_upozornenia_R__ {
            get {
                return ResourceManager.GetString("___Signalizacia_upozornenia_R__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilizacny cas.
        /// </summary>
        public static string ___Stabilizacny_cas__ {
            get {
                return ResourceManager.GetString("___Stabilizacny_cas__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard door.
        /// </summary>
        public static string ___Standard_door__ {
            get {
                return ResourceManager.GetString("___Standard_door__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start manual/Service mode.
        /// </summary>
        public static string ___Start_manual_Service_mode__ {
            get {
                return ResourceManager.GetString("___Start_manual_Service_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START MEASURE CT TRIGGER.
        /// </summary>
        public static string ___START_MEASURE_CT_TRIGGER__ {
            get {
                return ResourceManager.GetString("___START_MEASURE_CT_TRIGGER__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts automatic sequence. Before start you need to perform grounding sequence..
        /// </summary>
        public static string ___Starts_automatic_sequence__Before_start_you_need_to_perform_grounding_sequence___ {
            get {
                return ResourceManager.GetString("___Starts_automatic_sequence__Before_start_you_need_to_perform_grounding_sequence" +
                        "___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts suspend sequence of process(automatic,ground sequence)..
        /// </summary>
        public static string ___Starts_suspend_sequence_of_process_automatic_ground_sequence____ {
            get {
                return ResourceManager.GetString("___Starts_suspend_sequence_of_process_automatic_ground_sequence____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ___Status__ {
            get {
                return ResourceManager.GetString("___Status__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS INFO.
        /// </summary>
        public static string ___STATUS_INFO__ {
            get {
                return ResourceManager.GetString("___STATUS_INFO__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step mode.
        /// </summary>
        public static string ___Step_mode__ {
            get {
                return ResourceManager.GetString("___Step_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step mode is required because Service key position is set!.
        /// </summary>
        public static string ___Step_mode_is_required_because_Service_key_position_is_set___ {
            get {
                return ResourceManager.GetString("___Step_mode_is_required_because_Service_key_position_is_set___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step mode is required but mode key is not in required position!.
        /// </summary>
        public static string ___Step_mode_is_required_but_mode_key_is_not_in_required_position___ {
            get {
                return ResourceManager.GetString("___Step_mode_is_required_but_mode_key_is_not_in_required_position___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step mode is set or all are inactive!.
        /// </summary>
        public static string ___Step_mode_is_set_or_all_are_inactive___ {
            get {
                return ResourceManager.GetString("___Step_mode_is_set_or_all_are_inactive___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step time.
        /// </summary>
        public static string ___Step_time__ {
            get {
                return ResourceManager.GetString("___Step_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string ___Suspend__ {
            get {
                return ResourceManager.GetString("___Suspend__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUSPEND PROCESS.
        /// </summary>
        public static string ___SUSPEND_PROCESS__ {
            get {
                return ResourceManager.GetString("___SUSPEND_PROCESS__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend task.
        /// </summary>
        public static string ___Suspend_task__ {
            get {
                return ResourceManager.GetString("___Suspend_task__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend task has been done..
        /// </summary>
        public static string ___Suspend_task_has_been_done___ {
            get {
                return ResourceManager.GetString("___Suspend_task_has_been_done___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string ___Suspended__ {
            get {
                return ResourceManager.GetString("___Suspended__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUSPENDING COMPONENTS.
        /// </summary>
        public static string ___SUSPENDING_COMPONENTS__ {
            get {
                return ResourceManager.GetString("___SUSPENDING_COMPONENTS__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string ___Tag__ {
            get {
                return ResourceManager.GetString("___Tag__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Components.
        /// </summary>
        public static string ___Technology_Components__ {
            get {
                return ResourceManager.GetString("___Technology_Components__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology data.
        /// </summary>
        public static string ___Technology_data__ {
            get {
                return ResourceManager.GetString("___Technology_data__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test multi positions.
        /// </summary>
        public static string ___Test_multi_positions__ {
            get {
                return ResourceManager.GetString("___Test_multi_positions__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test positions.
        /// </summary>
        public static string ___Test_positions__ {
            get {
                return ResourceManager.GetString("___Test_positions__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string ___Timeout__ {
            get {
                return ResourceManager.GetString("___Timeout__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.
        /// </summary>
        public static string ___Unlocked__ {
            get {
                return ResourceManager.GetString("___Unlocked__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upevnenie zboku vstupneho blistra.
        /// </summary>
        public static string ___Upevnenie_zboku_vstupneho_blistra__ {
            get {
                return ResourceManager.GetString("___Upevnenie_zboku_vstupneho_blistra__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertikalny prisun vstupnych blistrov.
        /// </summary>
        public static string ___Vertikalny_prisun_vstupnych_blistrov__ {
            get {
                return ResourceManager.GetString("___Vertikalny_prisun_vstupnych_blistrov__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertikalny prisun vystupnych blistrov.
        /// </summary>
        public static string ___Vertikalny_prisun_vystupnych_blistrov__ {
            get {
                return ResourceManager.GetString("___Vertikalny_prisun_vystupnych_blistrov__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage is Off!.
        /// </summary>
        public static string ___Voltage_is_Off___ {
            get {
                return ResourceManager.GetString("___Voltage_is_Off___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vystupny blister je nad Bufferom.
        /// </summary>
        public static string ___Vystupny_blister_je_nad_Bufferom__ {
            get {
                return ResourceManager.GetString("___Vystupny_blister_je_nad_Bufferom__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vystupny blister neje v sklzovom dopravniku.
        /// </summary>
        public static string ___Vystupny_blister_neje_v_sklzovom_dopravniku__ {
            get {
                return ResourceManager.GetString("___Vystupny_blister_neje_v_sklzovom_dopravniku__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vystupny blister snimanie vo vytahu.
        /// </summary>
        public static string ___Vystupny_blister_snimanie_vo_vytahu__ {
            get {
                return ResourceManager.GetString("___Vystupny_blister_snimanie_vo_vytahu__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VYSTUPNY BUFFER - HORIZONTALNE ZASUNUTIE.
        /// </summary>
        public static string ___VYSTUPNY_BUFFER___HORIZONTALNE_ZASUNUTIE__ {
            get {
                return ResourceManager.GetString("___VYSTUPNY_BUFFER___HORIZONTALNE_ZASUNUTIE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VYSTUPNY BUFFER - KONTROLA POSCTU BLISTROV.
        /// </summary>
        public static string ___VYSTUPNY_BUFFER___KONTROLA_POSCTU_BLISTROV__ {
            get {
                return ResourceManager.GetString("___VYSTUPNY_BUFFER___KONTROLA_POSCTU_BLISTROV__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VYSTUPNY BUFFER - KONTROLA PRITOMNOSTI BLISTA NAD BUFFEROM.
        /// </summary>
        public static string ___VYSTUPNY_BUFFER___KONTROLA_PRITOMNOSTI_BLISTA_NAD_BUFFEROM__ {
            get {
                return ResourceManager.GetString("___VYSTUPNY_BUFFER___KONTROLA_PRITOMNOSTI_BLISTA_NAD_BUFFEROM__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VYSTUPNY BUFFER - POSUN KUSOV NAD BUFFER.
        /// </summary>
        public static string ___VYSTUPNY_BUFFER___POSUN_KUSOV_NAD_BUFFER__ {
            get {
                return ResourceManager.GetString("___VYSTUPNY_BUFFER___POSUN_KUSOV_NAD_BUFFER__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VYSTUPNY BUFFER - UVOLNENIE BLISTRA A NAVRAT NAHOR.
        /// </summary>
        public static string ___VYSTUPNY_BUFFER___UVOLNENIE_BLISTRA_A_NAVRAT_NAHOR__ {
            get {
                return ResourceManager.GetString("___VYSTUPNY_BUFFER___UVOLNENIE_BLISTRA_A_NAVRAT_NAHOR__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vystupny zasobnik je plny.
        /// </summary>
        public static string ___Vystupny_zasobnik_je_plny__ {
            get {
                return ResourceManager.GetString("___Vystupny_zasobnik_je_plny__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAITING FOR START.
        /// </summary>
        public static string ___WAITING_FOR_START__ {
            get {
                return ResourceManager.GetString("___WAITING_FOR_START__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to close and lock  all doors!.
        /// </summary>
        public static string ___Waiting_to_close_and_lock__all_doors___ {
            get {
                return ResourceManager.GetString("___Waiting_to_close_and_lock__all_doors___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to release recover button.
        /// </summary>
        public static string ___Waiting_to_release_recover_button__ {
            get {
                return ResourceManager.GetString("___Waiting_to_release_recover_button__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to release suspend button.
        /// </summary>
        public static string ___Waiting_to_release_suspend_button__ {
            get {
                return ResourceManager.GetString("___Waiting_to_release_suspend_button__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to unlock  all doors!.
        /// </summary>
        public static string ___Waiting_to_unlock__all_doors___ {
            get {
                return ResourceManager.GetString("___Waiting_to_unlock__all_doors___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ___Warning__ {
            get {
                return ResourceManager.GetString("___Warning__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was not founnd! Would you like still like to continue?.
        /// </summary>
        public static string ___was_not_founnd__Would_you_like_still_like_to_continue___ {
            get {
                return ResourceManager.GetString("___was_not_founnd__Would_you_like_still_like_to_continue___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to load default settings?.
        /// </summary>
        public static string ___Would_you_like_to_load_default_settings___ {
            get {
                return ResourceManager.GetString("___Would_you_like_to_load_default_settings___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknutue zhora vstupneho blistra.
        /// </summary>
        public static string ___Zamknutue_zhora_vstupneho_blistra__ {
            get {
                return ResourceManager.GetString("___Zamknutue_zhora_vstupneho_blistra__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamykanie blistra zhora neaktive (P9)(P9.1)je nepritomne.
        /// </summary>
        public static string ___Zamykanie_blistra_zhora_neaktive__P9__P9_1_je_nepritomne__ {
            get {
                return ResourceManager.GetString("___Zamykanie_blistra_zhora_neaktive__P9__P9_1_je_nepritomne__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zasobik blistrov prazdny.
        /// </summary>
        public static string ___Zasobik_blistrov_prazdny__ {
            get {
                return ResourceManager.GetString("___Zasobik_blistrov_prazdny__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string ___Zone__ {
            get {
                return ResourceManager.GetString("___Zone__", resourceCulture);
            }
        }
    }
}
