//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace x_template_xPlcConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("x_template_xPlcConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  already exist! .
        /// </summary>
        public static string ____already_exist____ {
            get {
                return ResourceManager.GetString("____already_exist____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Consecutive failure) The number of any recurring failure count has been reached!.
        /// </summary>
        public static string ____Consecutive_failure__The_number_of_any_recurring_failure_count_has_been_reached___ {
            get {
                return ResourceManager.GetString("____Consecutive_failure__The_number_of_any_recurring_failure_count_has_been_reach" +
                        "ed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Consecutive failure) The number of same recurring failure count has been reached! .
        /// </summary>
        public static string ____Consecutive_failure__The_number_of_same_recurring_failure_count_has_been_reached____ {
            get {
                return ResourceManager.GetString("____Consecutive_failure__The_number_of_same_recurring_failure_count_has_been_reac" +
                        "hed____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _cu00x.
        /// </summary>
        public static string ____cu00x__ {
            get {
                return ResourceManager.GetString("____cu00x__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is founded but assigned value is empty! Would you like continue? .
        /// </summary>
        public static string ____is_founded_but_assigned_value_is_empty__Would_you_like_continue____ {
            get {
                return ResourceManager.GetString("____is_founded_but_assigned_value_is_empty__Would_you_like_continue____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is inactive! .
        /// </summary>
        public static string ____is_inactive____ {
            get {
                return ResourceManager.GetString("____is_inactive____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not founded ! Would you like assign right now? .
        /// </summary>
        public static string ____is_not_founded___Would_you_like_assign_right_now____ {
            get {
                return ResourceManager.GetString("____is_not_founded___Would_you_like_assign_right_now____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not founded due collection is empty ! Would you like assign right now? .
        /// </summary>
        public static string ____is_not_founded_due_collection_is_empty___Would_you_like_assign_right_now____ {
            get {
                return ResourceManager.GetString("____is_not_founded_due_collection_is_empty___Would_you_like_assign_right_now____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was not founnd! Would you like still like to continue? .
        /// </summary>
        public static string ____was_not_founnd__Would_you_like_still_like_to_continue____ {
            get {
                return ResourceManager.GetString("____was_not_founnd__Would_you_like_still_like_to_continue____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW TAG  EXAMPLE.
        /// </summary>
        public static string ___ADD_NEW_TAG__EXAMPLE__ {
            get {
                return ResourceManager.GetString("___ADD_NEW_TAG__EXAMPLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Tag.
        /// </summary>
        public static string ___Adding_Tag__ {
            get {
                return ResourceManager.GetString("___Adding_Tag__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air pressure.
        /// </summary>
        public static string ___Air_pressure__ {
            get {
                return ResourceManager.GetString("___Air_pressure__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Value.
        /// </summary>
        public static string ___Assigned_Value__ {
            get {
                return ResourceManager.GetString("___Assigned_Value__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autmatic mode allowed.
        /// </summary>
        public static string ___Autmatic_mode_allowed__ {
            get {
                return ResourceManager.GetString("___Autmatic_mode_allowed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMAT.
        /// </summary>
        public static string ___AUTOMAT__ {
            get {
                return ResourceManager.GetString("___AUTOMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMAT ALL.
        /// </summary>
        public static string ___AUTOMAT_ALL__ {
            get {
                return ResourceManager.GetString("___AUTOMAT_ALL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average clean cycle time .
        /// </summary>
        public static string ___Average_clean_cycle_time___ {
            get {
                return ResourceManager.GetString("___Average_clean_cycle_time___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average cycle time .
        /// </summary>
        public static string ___Average_cycle_time___ {
            get {
                return ResourceManager.GetString("___Average_cycle_time___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average cycle time filter constant.
        /// </summary>
        public static string ___Average_cycle_time_filter_constant__ {
            get {
                return ResourceManager.GetString("___Average_cycle_time_filter_constant__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brings the device into basic position..
        /// </summary>
        public static string ___Brings_the_device_into_basic_position___ {
            get {
                return ResourceManager.GetString("___Brings_the_device_into_basic_position___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        public static string ___Carrier__ {
            get {
                return ResourceManager.GetString("___Carrier__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean loop time.
        /// </summary>
        public static string ___Clean_loop_time__ {
            get {
                return ResourceManager.GetString("___Clean_loop_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control voltage.
        /// </summary>
        public static string ___Control_voltage__ {
            get {
                return ResourceManager.GetString("___Control_voltage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ___Created__ {
            get {
                return ResourceManager.GetString("___Created__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CU00x.
        /// </summary>
        public static string ___CU00x__ {
            get {
                return ResourceManager.GetString("___CU00x__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle time.
        /// </summary>
        public static string ___Cycle_time__ {
            get {
                return ResourceManager.GetString("___Cycle_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors closed.
        /// </summary>
        public static string ___Doors_closed__ {
            get {
                return ResourceManager.GetString("___Doors_closed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors locked.
        /// </summary>
        public static string ___Doors_locked__ {
            get {
                return ResourceManager.GetString("___Doors_locked__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop.
        /// </summary>
        public static string ___Emergency_stop__ {
            get {
                return ResourceManager.GetString("___Emergency_stop__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string ___Empty__ {
            get {
                return ResourceManager.GetString("___Empty__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy saving mode - Inactivity time.
        /// </summary>
        public static string ___Energy_saving_mode___Inactivity_time__ {
            get {
                return ResourceManager.GetString("___Energy_saving_mode___Inactivity_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity header.
        /// </summary>
        public static string ___Entity_header__ {
            get {
                return ResourceManager.GetString("___Entity_header__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ___Error__ {
            get {
                return ResourceManager.GetString("___Error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded tag .
        /// </summary>
        public static string ___Founded_tag___ {
            get {
                return ResourceManager.GetString("___Founded_tag___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUND.
        /// </summary>
        public static string ___GROUND__ {
            get {
                return ResourceManager.GetString("___GROUND__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUND ALL.
        /// </summary>
        public static string ___GROUND_ALL__ {
            get {
                return ResourceManager.GetString("___GROUND_ALL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart beat.
        /// </summary>
        public static string ___Heart_beat__ {
            get {
                return ResourceManager.GetString("___Heart_beat__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDLE.
        /// </summary>
        public static string ___IDLE__ {
            get {
                return ResourceManager.GetString("___IDLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key UID.
        /// </summary>
        public static string ___Key_UID__ {
            get {
                return ResourceManager.GetString("___Key_UID__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Rework Name.
        /// </summary>
        public static string ___Last_Rework_Name__ {
            get {
                return ResourceManager.GetString("___Last_Rework_Name__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last station.
        /// </summary>
        public static string ___Last_station__ {
            get {
                return ResourceManager.GetString("___Last_station__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light curtain.
        /// </summary>
        public static string ___Light_curtain__ {
            get {
                return ResourceManager.GetString("___Light_curtain__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUAL.
        /// </summary>
        public static string ___MANUAL__ {
            get {
                return ResourceManager.GetString("___MANUAL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string ___Master__ {
            get {
                return ResourceManager.GetString("___Master__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max allowed number of any recurring failures (consecutive).
        /// </summary>
        public static string ___Max_allowed_number_of_any_recurring_failures__consecutive___ {
            get {
                return ResourceManager.GetString("___Max_allowed_number_of_any_recurring_failures__consecutive___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max allowed number of same recurring failures (consecutive).
        /// </summary>
        public static string ___Max_allowed_number_of_same_recurring_failures__consecutive___ {
            get {
                return ResourceManager.GetString("___Max_allowed_number_of_same_recurring_failures__consecutive___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string ___Modified__ {
            get {
                return ResourceManager.GetString("___Modified__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next on Failed.
        /// </summary>
        public static string ___Next_on_Failed__ {
            get {
                return ResourceManager.GetString("___Next_on_Failed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next on Passed.
        /// </summary>
        public static string ___Next_on_Passed__ {
            get {
                return ResourceManager.GetString("___Next_on_Passed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next station.
        /// </summary>
        public static string ___Next_station__ {
            get {
                return ResourceManager.GetString("___Next_station__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal.
        /// </summary>
        public static string ___Nominal__ {
            get {
                return ResourceManager.GetString("___Nominal__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation ended.
        /// </summary>
        public static string ___Operation_ended__ {
            get {
                return ResourceManager.GetString("___Operation_ended__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation started.
        /// </summary>
        public static string ___Operation_started__ {
            get {
                return ResourceManager.GetString("___Operation_started__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations opened.
        /// </summary>
        public static string ___Operations_opened__ {
            get {
                return ResourceManager.GetString("___Operations_opened__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAIR TAG WITH ASSIGNED VALUE EXAMPLE.
        /// </summary>
        public static string ___PAIR_TAG_WITH_ASSIGNED_VALUE_EXAMPLE__ {
            get {
                return ResourceManager.GetString("___PAIR_TAG_WITH_ASSIGNED_VALUE_EXAMPLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing Tag.
        /// </summary>
        public static string ___Pairing_Tag__ {
            get {
                return ResourceManager.GetString("___Pairing_Tag__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Position.
        /// </summary>
        public static string ___Pick_Position__ {
            get {
                return ResourceManager.GetString("___Pick_Position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place  Position.
        /// </summary>
        public static string ___Place__Position__ {
            get {
                return ResourceManager.GetString("___Place__Position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please acknowledge recurring failure!.
        /// </summary>
        public static string ___Please_acknowledge_recurring_failure___ {
            get {
                return ResourceManager.GetString("___Please_acknowledge_recurring_failure___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please acknowledge recurring failure! .
        /// </summary>
        public static string ___Please_acknowledge_recurring_failure____ {
            get {
                return ResourceManager.GetString("___Please_acknowledge_recurring_failure____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process data.
        /// </summary>
        public static string ___Process_data__ {
            get {
                return ResourceManager.GetString("___Process_data__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process data not selected.
        /// </summary>
        public static string ___Process_data_not_selected__ {
            get {
                return ResourceManager.GetString("___Process_data_not_selected__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production planer.
        /// </summary>
        public static string ___Production_planer__ {
            get {
                return ResourceManager.GetString("___Production_planer__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production planer completed required plan! .
        /// </summary>
        public static string ___Production_planer_completed_required_plan____ {
            get {
                return ResourceManager.GetString("___Production_planer_completed_required_plan____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production planer is empty! .
        /// </summary>
        public static string ___Production_planer_is_empty____ {
            get {
                return ResourceManager.GetString("___Production_planer_is_empty____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READY TO START.
        /// </summary>
        public static string ___READY_TO_START__ {
            get {
                return ResourceManager.GetString("___READY_TO_START__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        public static string ___Recipe__ {
            get {
                return ResourceManager.GetString("___Recipe__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe created.
        /// </summary>
        public static string ___Recipe_created__ {
            get {
                return ResourceManager.GetString("___Recipe_created__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe modified.
        /// </summary>
        public static string ___Recipe_modified__ {
            get {
                return ResourceManager.GetString("___Recipe_modified__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ___Reset__ {
            get {
                return ResourceManager.GetString("___Reset__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ___Results__ {
            get {
                return ResourceManager.GetString("___Results__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rework Count.
        /// </summary>
        public static string ___Rework_Count__ {
            get {
                return ResourceManager.GetString("___Rework_Count__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reworked.
        /// </summary>
        public static string ___Reworked__ {
            get {
                return ResourceManager.GetString("___Reworked__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety doors OK.
        /// </summary>
        public static string ___Safety_doors_OK__ {
            get {
                return ResourceManager.GetString("___Safety_doors_OK__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start manual/Service mode.
        /// </summary>
        public static string ___Start_manual_Service_mode__ {
            get {
                return ResourceManager.GetString("___Start_manual_Service_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START MEASURE CT TRIGGER.
        /// </summary>
        public static string ___START_MEASURE_CT_TRIGGER__ {
            get {
                return ResourceManager.GetString("___START_MEASURE_CT_TRIGGER__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts automatic sequence. Before start you need to perform grounding sequence..
        /// </summary>
        public static string ___Starts_automatic_sequence__Before_start_you_need_to_perform_grounding_sequence___ {
            get {
                return ResourceManager.GetString("___Starts_automatic_sequence__Before_start_you_need_to_perform_grounding_sequence" +
                        "___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ___Status__ {
            get {
                return ResourceManager.GetString("___Status__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS INFO.
        /// </summary>
        public static string ___STATUS_INFO__ {
            get {
                return ResourceManager.GetString("___STATUS_INFO__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step time.
        /// </summary>
        public static string ___Step_time__ {
            get {
                return ResourceManager.GetString("___Step_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag .
        /// </summary>
        public static string ___Tag___ {
            get {
                return ResourceManager.GetString("___Tag___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology data.
        /// </summary>
        public static string ___Technology_data__ {
            get {
                return ResourceManager.GetString("___Technology_data__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test multi positions.
        /// </summary>
        public static string ___Test_multi_positions__ {
            get {
                return ResourceManager.GetString("___Test_multi_positions__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test positions.
        /// </summary>
        public static string ___Test_positions__ {
            get {
                return ResourceManager.GetString("___Test_positions__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ___Warning__ {
            get {
                return ResourceManager.GetString("___Warning__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to load default settings?.
        /// </summary>
        public static string ___Would_you_like_to_load_default_settings___ {
            get {
                return ResourceManager.GetString("___Would_you_like_to_load_default_settings___", resourceCulture);
            }
        }
    }
}
