//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace x_template_xStatistic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("x_template_xStatistic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALCULATED .
        /// </summary>
        public static string CalculatedCount {
            get {
                return ResourceManager.GetString("CalculatedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARRIER.
        /// </summary>
        public static string Carrier {
            get {
                return ResourceManager.GetString("Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARRIER COUNTER.
        /// </summary>
        public static string CarrierCounter {
            get {
                return ResourceManager.GetString("CarrierCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET .
        /// </summary>
        public static string ClearCounter {
            get {
                return ResourceManager.GetString("ClearCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTERS.
        /// </summary>
        public static string Counters {
            get {
                return ResourceManager.GetString("Counters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED/HOUR.
        /// </summary>
        public static string CountFailedPerHour {
            get {
                return ResourceManager.GetString("CountFailedPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSED/HOUR.
        /// </summary>
        public static string CountPassedPerHour {
            get {
                return ResourceManager.GetString("CountPassedPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR COUNTER.
        /// </summary>
        public static string ErrorCounter {
            get {
                return ResourceManager.GetString("ErrorCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR RATE [%].
        /// </summary>
        public static string ErrorRate {
            get {
                return ResourceManager.GetString("ErrorRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOUR COUNTER.
        /// </summary>
        public static string HourCunter {
            get {
                return ResourceManager.GetString("HourCunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSED.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCTION TREND.
        /// </summary>
        public static string ProductionTrend {
            get {
                return ResourceManager.GetString("ProductionTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE OF PRODUCTION COUNTER.
        /// </summary>
        public static string ProductionType {
            get {
                return ResourceManager.GetString("ProductionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REAL PRODUCTON TARGET [%].
        /// </summary>
        public static string RealProductionTarget {
            get {
                return ResourceManager.GetString("RealProductionTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIRED HOUR PRODUCTION.
        /// </summary>
        public static string RequiredHourProduction {
            get {
                return ResourceManager.GetString("RequiredHourProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REWORK.
        /// </summary>
        public static string Rework {
            get {
                return ResourceManager.GetString("Rework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REWORK COUNTER.
        /// </summary>
        public static string ReworkCounter {
            get {
                return ResourceManager.GetString("ReworkCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOURS AND SHIFTS .
        /// </summary>
        public static string SetHourToShift {
            get {
                return ResourceManager.GetString("SetHourToShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIFT.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPLIT ERROR COUNTERS.
        /// </summary>
        public static string SplitErrorCounter {
            get {
                return ResourceManager.GetString("SplitErrorCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THREE SHHIFT A DAY.
        /// </summary>
        public static string ThreeShiftCounter {
            get {
                return ResourceManager.GetString("ThreeShiftCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME PERIOD.
        /// </summary>
        public static string TimePeriod {
            get {
                return ResourceManager.GetString("TimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCTION TREND .
        /// </summary>
        public static string Trend {
            get {
                return ResourceManager.GetString("Trend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWO SHIFT COUNTER A DAY.
        /// </summary>
        public static string TwoShiftCounter {
            get {
                return ResourceManager.GetString("TwoShiftCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE ID.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE COUNTERS.
        /// </summary>
        public static string TypeCounter {
            get {
                return ResourceManager.GetString("TypeCounter", resourceCulture);
            }
        }
    }
}
