//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace x_template_xOp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationPanel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("x_template_xOp.Properties.NotificationPanel", typeof(NotificationPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air pressure.
        /// </summary>
        public static string AirPressure {
            get {
                return ResourceManager.GetString("AirPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic mode.
        /// </summary>
        public static string AutomaticMode {
            get {
                return ResourceManager.GetString("AutomaticMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control voltage.
        /// </summary>
        public static string ControlVoltage {
            get {
                return ResourceManager.GetString("ControlVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors closed.
        /// </summary>
        public static string DoorClosed {
            get {
                return ResourceManager.GetString("DoorClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors locked.
        /// </summary>
        public static string DoorLocked {
            get {
                return ResourceManager.GetString("DoorLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop.
        /// </summary>
        public static string EmergencyStop {
            get {
                return ResourceManager.GetString("EmergencyStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart beat.
        /// </summary>
        public static string HeartBeat {
            get {
                return ResourceManager.GetString("HeartBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light curtain.
        /// </summary>
        public static string LightCurtain {
            get {
                return ResourceManager.GetString("LightCurtain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulator.
        /// </summary>
        public static string Manipulator {
            get {
                return ResourceManager.GetString("Manipulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process data.
        /// </summary>
        public static string ProcessData {
            get {
                return ResourceManager.GetString("ProcessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety doors.
        /// </summary>
        public static string SafetyDoorOk {
            get {
                return ResourceManager.GetString("SafetyDoorOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology data.
        /// </summary>
        public static string TechnologyData {
            get {
                return ResourceManager.GetString("TechnologyData", resourceCulture);
            }
        }
    }
}
