<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Cu00xTestPositions" Id="{4fd6a69c-a695-462f-a5d8-c710bf5e640a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Cu00xTestPositions EXTENDS TcoDrivesBeckhoff.TcoSingleAxisPositionsRootContainer
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	{attribute addProperty Name "<#Pick Position#>"}
	PickPosition:TcoDrivesBeckhoff.TcoMultiAxisMoveParam;
	{attribute addProperty Name "<#Place  Position#>"}
	PlacePosition:TcoDrivesBeckhoff.TcoMultiAxisMoveParam;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>