<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CU00xRecoverTask" Id="{17c9c1d5-2003-4c5d-8cd0-01016f658adf}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK CU00xRecoverTask EXTENDS CUBaseRecover IMPLEMENTS ICUTask
VAR
	_sb : TcoCore.StringBuilder;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Run();
]]></ST>
    </Implementation>
    <Method Name="Main" Id="{53763c9c-9c67-4ee3-bca2-4a5dbd72caf9}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Main method of the sequener. Custom code needs to be placed here. The sequencer is executed by call of **Instance.Run()** method.
			This method is abstract, and it must be overridden in derived block.
		</summary>
	</docu>
~*)
METHOD PROTECTED Main : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[(*

	RECOVER PROCESS 
	Following steps provide recover action for this controlled unit.
	Add components add write customized sequence according to your need.
*)

		
//
IF (Step(100, TRUE, '<#WAITING FOR START#>')) THEN
    //-------------------------------------    

    StepCompleteWhen(TRUE);
    //-------------------------------------
END_IF

//HERE  YOU CAN WRITE  WHAT IS NECESSARY 
//TO RECOVER AFTER INTERUPTED PROCESS.....

IF (Step(1000, TRUE, '<#RECOVER ANY COMPONENTS#>')) THEN
    //-------------------------------------    

    StepCompleteWhen(CurrentStep.Duration >= T#3000MS);
    //-------------------------------------
END_IF

IF (Step(30000, TRUE, 'RECOVER DONE')) THEN
    //-------------------------------------
		
        this^._done:=true;
		THIS^.Task.DoneWhen(TRUE);
		
   
    //-------------------------------------	
END_IF
]]></ST>
      </Implementation>
    </Method>
    <Method Name="OnStart" Id="{12984ff7-8aaf-4d54-afb8-14128dc747b1}">
      <Declaration><![CDATA[METHOD PUBLIC OnStart

]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.OnStart();
Station.SuspendTask.Restore();

]]></ST>
      </Implementation>
    </Method>
    <Property Name="Station" Id="{febe1bf1-9517-4676-b744-277f3b895ad5}">
      <Declaration><![CDATA[PROPERTY Station : REFERENCE TO CU00x]]></Declaration>
      <Get Name="Get" Id="{e2565e34-ebfa-4e3d-80c3-081845ce4425}">
        <Declaration><![CDATA[VAR
    _station : POINTER TO CU00x;
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IF __QUERYPOINTER(Parent, _station) THEN // Check if _Parent is Station001
    Station REF= _station^;              // If the check is successful dereference a pointer. simlar to THIS^ or SUPER^
END_IF]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>