name: release

on: 
  push:
    branches : 
      - release
  pull_request: 
    paths:
      - 'src/**'
      - 'pipelines/**'
      - '.github/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with :
          path : '.'
          fetch-depth: 0
      - name: Cake
        env:
          gh-public-repos: ${{ secrets.TCOPENTEMPLATESPAT  }}
	        TCOOPENNUGETDOTORGPAT : ${{ secrets.TCOOPENNUGETDOTORGPAT  }}
        run: >
          .\build.ps1  